package net.minecraft.src;

public class BTAGenLayerShore extends BTAGenLayer
{
	public BTAGenLayerShore(long par1, GenLayer par3GenLayer)
	{
		super(par1);
		this.parent = par3GenLayer;
	}

	/**
	 * Returns a list of integer values generated by this layer. These may be interpreted as temperatures, rainfall
	 * amounts, or biomeList[] indices based on the particular GenLayer subclass.
	 */
	public int[] getInts(int par1, int par2, int par3, int par4)
	{
		int[] parentInts = this.parent.getInts(par1 - 1, par2 - 1, par3 + 2, par4 + 2);
		int[] intCache = IntCache.getIntCache(par3 * par4);

		for (int i = 0; i < par4; ++i)
		{
			for (int j = 0; j < par3; ++j)
			{
				this.initChunkSeed((long)(j + par1), (long)(i + par2));
				int currentBiome = parentInts[j + 1 + (i + 1) * (par3 + 2)];
				int var10;
				int var11;
				int var12;
				int var13;

				if (currentBiome == BiomeGenBase.mushroomIsland.biomeID)
				{
					var10 = parentInts[j + 1 + (i + 1 - 1) * (par3 + 2)];
					var11 = parentInts[j + 1 + 1 + (i + 1) * (par3 + 2)];
					var12 = parentInts[j + 1 - 1 + (i + 1) * (par3 + 2)];
					var13 = parentInts[j + 1 + (i + 1 + 1) * (par3 + 2)];

					if (var10 != BiomeGenBase.ocean.biomeID && var11 != BiomeGenBase.ocean.biomeID && var12 != BiomeGenBase.ocean.biomeID && var13 != BiomeGenBase.ocean.biomeID)
					{
						intCache[j + i * par3] = currentBiome;
					}
					else
					{
						intCache[j + i * par3] = BiomeGenBase.mushroomIslandShore.biomeID;
					}
				}
				else if (currentBiome != BiomeGenBase.ocean.biomeID && currentBiome != BiomeGenBase.river.biomeID && currentBiome != BiomeGenBase.swampland.biomeID && currentBiome != BiomeGenBase.extremeHills.biomeID && BTABiomeConfiguration.getEdgeVariantForBiome(currentBiome) == -1)
				{
					var10 = parentInts[j + 1 + (i + 1 - 1) * (par3 + 2)];
					var11 = parentInts[j + 1 + 1 + (i + 1) * (par3 + 2)];
					var12 = parentInts[j + 1 - 1 + (i + 1) * (par3 + 2)];
					var13 = parentInts[j + 1 + (i + 1 + 1) * (par3 + 2)];

					if (var10 != BiomeGenBase.ocean.biomeID && var11 != BiomeGenBase.ocean.biomeID && var12 != BiomeGenBase.ocean.biomeID && var13 != BiomeGenBase.ocean.biomeID)
					{
						intCache[j + i * par3] = currentBiome;
					}
					else
					{
						if (BTABiomeConfiguration.getBeachVariantForBiomes(currentBiome) != -1) {
							intCache[j + i * par3] = BTABiomeConfiguration.getBeachVariantForBiomes(currentBiome);
						}
						else if (BTABiomeConfiguration.shouldBiomeSpawnBeach(currentBiome)){
							intCache[j + i * par3] = BiomeGenBase.beach.biomeID;
						}
						else {
							intCache[j + i * par3] = currentBiome;
						}
					}
				}
				else if (currentBiome == BiomeGenBase.extremeHills.biomeID)
				{
					var10 = parentInts[j + 1 + (i + 1 - 1) * (par3 + 2)];
					var11 = parentInts[j + 1 + 1 + (i + 1) * (par3 + 2)];
					var12 = parentInts[j + 1 - 1 + (i + 1) * (par3 + 2)];
					var13 = parentInts[j + 1 + (i + 1 + 1) * (par3 + 2)];

					if (var10 == BiomeGenBase.extremeHills.biomeID && var11 == BiomeGenBase.extremeHills.biomeID && var12 == BiomeGenBase.extremeHills.biomeID && var13 == BiomeGenBase.extremeHills.biomeID)
					{
						intCache[j + i * par3] = currentBiome;
					}
					else
					{
						intCache[j + i * par3] = BiomeGenBase.extremeHillsEdge.biomeID;
					}
				}
				else
				{
					var10 = parentInts[j + 1 + (i + 1 - 1) * (par3 + 2)];
					var11 = parentInts[j + 1 + 1 + (i + 1) * (par3 + 2)];
					var12 = parentInts[j + 1 - 1 + (i + 1) * (par3 + 2)];
					var13 = parentInts[j + 1 + (i + 1 + 1) * (par3 + 2)];
					
					//If all surrounding biomes are the same as the current biome do not form an edge
					if (var10 == currentBiome && var11 == currentBiome && var12 == currentBiome && var13 == currentBiome) {
						intCache[j + i * par3] = currentBiome;
					}
					//If an edge can be formed with any of the adjacent biomes
					else if ((BTABiomeConfiguration.shouldBiomeConnectWithEdge(var10)) ||
								(BTABiomeConfiguration.shouldBiomeConnectWithEdge(var11)) ||
								(BTABiomeConfiguration.shouldBiomeConnectWithEdge(var12)) ||
								(BTABiomeConfiguration.shouldBiomeConnectWithEdge(var13)) ||
							BTABiomeConfiguration.doesBiomeIgnoreEdgeRestrictions(currentBiome))
					{
						//If current biome is a biome that forms edges
						if (BTABiomeConfiguration.getEdgeVariantForBiome(currentBiome) != -1) {
							intCache[j + i * par3] = BTABiomeConfiguration.getEdgeVariantForBiome(currentBiome);
						}
						else {
							intCache[j + i * par3] = currentBiome;
						}
					}
					else {
						intCache[j + i * par3] = currentBiome;
					}
				}
			}
		}

		return intCache;
	}
}
