package betterterrain.biome.layer;

import betterterrain.BTAVersion;
import betterterrain.biome.BTABiome;
import betterterrain.biome.BiomeConfiguration;
import betterterrain.world.config.WorldConfigurationInfo;
import net.minecraft.src.BiomeGenBase;
import net.minecraft.src.GenLayer;
import net.minecraft.src.IntCache;

public class ShoreLayer extends BTALayer
{
	private WorldConfigurationInfo generatorInfo;
	private int passNum;
	
	public ShoreLayer(long par1, GenLayer parent, WorldConfigurationInfo generatorInfo, int pass)
	{
		super(par1);
		this.parent = parent;
        this.generatorInfo = generatorInfo;
        this.passNum = pass;
	}

	/**
	 * Returns a list of integer values generated by this layer. These may be interpreted as temperatures, rainfall
	 * amounts, or biomeList[] indices based on the particular GenLayer subclass.
	 */
	public int[] getInts(int xOffset, int zOffset, int xSize, int zSize)
	{
		int[] parentInts = this.parent.getInts(xOffset - 1, zOffset - 1, xSize + 2, zSize + 2);
		int[] intCache = IntCache.getIntCache(xSize * zSize);

		for (int i = 0; i < zSize; ++i)
		{
			for (int j = 0; j < xSize; ++j)
			{
				this.initChunkSeed((long)(j + xOffset), (long)(i + zOffset));
				int currentBiome = parentInts[j + 1 + (i + 1) * (xSize + 2)];
				int neighbor1;
				int neighbor2;
				int neighbor3;
				int neighbor4;

				if (currentBiome == BiomeGenBase.mushroomIsland.biomeID)
				{
					neighbor1 = parentInts[j + 1 + (i + 1 - 1) * (xSize + 2)];
					neighbor2 = parentInts[j + 1 + 1 + (i + 1) * (xSize + 2)];
					neighbor3 = parentInts[j + 1 - 1 + (i + 1) * (xSize + 2)];
					neighbor4 = parentInts[j + 1 + (i + 1 + 1) * (xSize + 2)];

					if (neighbor1 != BiomeGenBase.ocean.biomeID && neighbor2 != BiomeGenBase.ocean.biomeID && neighbor3 != BiomeGenBase.ocean.biomeID && neighbor4 != BiomeGenBase.ocean.biomeID)
					{
						intCache[j + i * xSize] = currentBiome;
					}
					else
					{
						intCache[j + i * xSize] = BiomeGenBase.mushroomIslandShore.biomeID;
					}
				}
				else if (currentBiome != BiomeGenBase.ocean.biomeID && BiomeConfiguration.getEdgeVariantForBiomes(currentBiome, this.generatorInfo, this) == currentBiome)
				{
					neighbor1 = parentInts[j + 1 + (i + 1 - 1) * (xSize + 2)];
					neighbor2 = parentInts[j + 1 + 1 + (i + 1) * (xSize + 2)];
					neighbor3 = parentInts[j + 1 - 1 + (i + 1) * (xSize + 2)];
					neighbor4 = parentInts[j + 1 + (i + 1 + 1) * (xSize + 2)];

					if (neighbor1 != BiomeGenBase.ocean.biomeID && neighbor2 != BiomeGenBase.ocean.biomeID && neighbor3 != BiomeGenBase.ocean.biomeID && neighbor4 != BiomeGenBase.ocean.biomeID)
					{
						intCache[j + i * xSize] = currentBiome;
					}
					else
					{
						if (BiomeConfiguration.getBeachVariantForBiomes(currentBiome, generatorInfo, this) != currentBiome || (BiomeGenBase.biomeList[currentBiome] instanceof BTABiome && ((BTABiome) BiomeGenBase.biomeList[currentBiome]).isBeach())) {
							intCache[j + i * xSize] = BiomeConfiguration.getBeachVariantForBiomes(currentBiome, generatorInfo, this);
						}
						else if (BiomeConfiguration.shouldBiomeSpawnBeach(currentBiome, this.generatorInfo, this)){
							intCache[j + i * xSize] = BiomeGenBase.beach.biomeID;
						}
						else {
							intCache[j + i * xSize] = currentBiome;
						}
					}
				}
				else
				{
					neighbor1 = parentInts[j + 1 + (i + 1 - 1) * (xSize + 2)];
					neighbor2 = parentInts[j + 1 + 1 + (i + 1) * (xSize + 2)];
					neighbor3 = parentInts[j + 1 - 1 + (i + 1) * (xSize + 2)];
					neighbor4 = parentInts[j + 1 + (i + 1 + 1) * (xSize + 2)];
					
					//If all surrounding biomes are the same as the current biome do not form an edge
					if (neighbor1 == currentBiome && neighbor2 == currentBiome && neighbor3 == currentBiome && neighbor4 == currentBiome) {
						intCache[j + i * xSize] = currentBiome;
					}
					//If an edge can be formed with any of the adjacent biomes
					else if ((BiomeConfiguration.shouldBiomeConnectWithEdge(neighbor1, this.generatorInfo, this)) ||
								(BiomeConfiguration.shouldBiomeConnectWithEdge(neighbor2, this.generatorInfo, this)) ||
								(BiomeConfiguration.shouldBiomeConnectWithEdge(neighbor3, this.generatorInfo, this)) ||
								(BiomeConfiguration.shouldBiomeConnectWithEdge(neighbor4, this.generatorInfo, this)))
					{
						//If current biome is a biome that forms edges
						if (BiomeConfiguration.getEdgeVariantForBiomes(currentBiome, this.generatorInfo, this) != currentBiome) {
							if (this.generatorInfo.getBTAVersion().isVersionAtOrBelow(BTAVersion.V3_1_0)
									|| passNum == 1
									|| (BiomeGenBase.biomeList[currentBiome] instanceof BTABiome
											&& ((BTABiome) BiomeGenBase.biomeList[currentBiome]).hasExtendedEdge()))
							{
								intCache[j + i * xSize] = BiomeConfiguration.getEdgeVariantForBiomes(currentBiome, this.generatorInfo, this);
							}
							else {
								intCache[j + i * xSize] = currentBiome;
							}
						}
						else {
							intCache[j + i * xSize] = currentBiome;
						}
					}
					else {
						intCache[j + i * xSize] = currentBiome;
					}
				}
			}
		}

		return intCache;
	}
}
