package betterterrain.biome.layer;

import net.minecraft.src.IntCache;

public class HorizonsContinentLayer extends HorizonsLayer
{
    public HorizonsContinentLayer(long par1)
    {
        super(par1);
    }

    /**
     * Returns a list of integer values generated by this layer. These may be interpreted as temperatures, rainfall
     * amounts, or biomeList[] indices based on the particular GenLayer subclass.
     */
    public int[] getInts(int x, int z, int sizeX, int sizeZ)
    {
        int[] intCache = IntCache.getIntCache(sizeX * sizeZ);

        for (int k = 0; k < sizeZ; ++k)
        {
            for (int i = 0; i < sizeX; ++i)
            {
                this.initChunkSeed((long)(x + i), (long)(z + k));
                intCache[i + k * sizeX] = this.nextInt(4) == 0 ? 1 : 0;
            }
        }

        if (x > -sizeX && x <= 0 && z > -sizeZ && z <= 0)
        {
            intCache[-x + -z * sizeX] = 1;
        }

        return intCache;
    }
}
