package betterterrain.biome.layer;

import betterterrain.BTAVersion;
import betterterrain.biome.BiomeConfiguration;
import betterterrain.world.WorldConfigurationInfo;
import net.minecraft.src.GenLayer;
import net.minecraft.src.IntCache;

public class SporadicLayer extends GenLayer
{
	private WorldConfigurationInfo generatorInfo;
	
    public SporadicLayer(long baseSeed, GenLayer parent, WorldConfigurationInfo generatorInfo) {
        super(baseSeed);
        this.parent = parent;
        this.generatorInfo = generatorInfo;
    }

    /**
     * Returns a list of integer values generated by this layer. These may be interpreted as temperatures, rainfall
     * amounts, or biomeList[] indices based on the particular GenLayer subclass.
     */
    public int[] getInts(int xOffset, int zOffset, int xSize, int zSize) {
        int[] parentInts = this.parent.getInts(xOffset - 1, zOffset - 1, xSize + 2, zSize + 2);
        int[] cache = IntCache.getIntCache(xSize * zSize);

        for (int i = 0; i < zSize; ++i) {
            for (int k = 0; k < xSize; ++k) {
                this.initChunkSeed((long)(k + xOffset), (long)(i + zOffset));
                int currentBiome = parentInts[k + 1 + (i + 1) * (xSize + 2)];

                if (BiomeConfiguration.getSporadicVariantForBiome(currentBiome) != -1 && this.nextInt(BiomeConfiguration.getSporadicChanceForBiome(currentBiome)) == 0 && generatorInfo.getCompatMode().isVersionAtLeast(BTAVersion.V1_3_0)) {
                    cache[k + i * xSize] = BiomeConfiguration.getSporadicVariantForBiome(currentBiome);
                }
                else {
                    cache[k + i * xSize] = currentBiome;
                }
            }
        }

        return cache;
    }
}
